# Generated by Django 5.2 on 2026-07-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/noimage.png', upload_to='images/'),
        ),
    ]
